### ISSUE TITLE
Design a Road map For CS-Fundamentals

### ISSUE THREAD

**Issue by OmarShawky1** [alikehel/activecourses#9]
Design a road map for CS-Fundamentals using any road map app the exports an html. The best option that we found is roadmap.sh.

The contributor is requested to use the content in [CS-Fundamentals](https://www.activecourses.tech/resources/courses/cs-fundamentals#courses) and the [Table](https://www.activecourses.tech/resources/courses/cs-fundamentals#cs-fundamentals) to draw a map using roadmap.sh and export the markdown format used to draw it like in the following picture.

![image](https://github.com/alikehel/activecourses/assets/51538094/8b4ae0ab-1349-49a4-a3f4-81d385a89bb8)

**Comment by ahmedsiam0** [comment]
I have created it but lost the markdown text that i used to generate the roadmap.

roadmap.sh doesn't depend in markdown as a file format, it is just to generate the initial roadmap, after that you have to edit the roadmap visually. (it doesn't save this markdown text after you close the season, just saves the resulted roadmap)

here is what i created:
https://roadmap.sh/r?id=657732ed5145316d25eb0387

Maybe this roadmap should be some kind of groups like neetcode list where topics are groups that has courses inside (instead of tree-like roadmap) (Maybe it would be hard-coded).
https://neetcode.io/practice

**Comment by OmarShawky1** [comment]
Resolved in #11 by @ahmedsiam0
